#!/bin/bash

echo "🖼️  PHOTO INSTALLATION GUIDE"
echo "================================"
echo ""
echo "Your portfolio is running at: http://localhost:8001"
echo ""
echo "📂 TO ADD YOUR PHOTO:"
echo "1. Open Finder"
echo "2. Go to: /Users/akjaiswal/Desktop/ALL DATA/"
echo "3. Find: imsgr,im.jpeg"
echo "4. Copy it (Cmd+C)"
echo "5. Go to: /Users/akjaiswal/Desktop/resume/assets/"
echo "6. Paste it (Cmd+V)"
echo "7. Rename to: Ayush.png"
echo "8. Refresh your browser"
echo ""
echo "✨ Your photo will appear in:"
echo "   - Hero section profile"
echo "   - Navigation logo area"
echo "   - All responsive views"
echo ""
echo "🔧 Alternative terminal command:"
echo 'cp "/Users/akjaiswal/Desktop/ALL DATA/imsgr,im.jpeg" "/Users/akjaiswal/Desktop/resume/assets/Ayush.png"'
echo ""
echo "📏 Photo will be automatically resized to fit perfectly!"
